import { describe, expect, it } from "vitest"
import { renderInfo } from "../../../src/core/declarations/info"

describe("renderInfo", () => {
  it("renders title + version + separator + generated marker", () => {
    expect(renderInfo({ title: "T", version: "1.0", description: "D" })).toBe(
      "// T\n// Version: 1.0\n// ------\n// Generated by openapi-shape.",
    )
  })

  it("emits only the generated marker when info is empty (no separator)", () => {
    expect(renderInfo({})).toBe("// Generated by openapi-shape.")
  })

  it("collapses multi-line title into a single line", () => {
    expect(renderInfo({ title: "Line 1\nLine 2" })).toBe(
      "// Line 1 Line 2\n// ------\n// Generated by openapi-shape.",
    )
  })
})
