import { describe, expect, it } from "vitest";
import { renderInfo } from "../../../src/core/declarations/info";

describe("renderInfo: default", () => {
  it("renders title + version + description + @generated", () => {
    expect(renderInfo({ title: "T", version: "1.0", description: "D" })).toBe(
      "/**\n * T\n *\n * @version 1.0\n * @description D\n * @generated by openapi-shape.\n */",
    );
  });
  it("renders @generated only when info is empty", () => {
    expect(renderInfo({})).toBe("/**\n * @generated by openapi-shape.\n */");
  });
  it("expands multi-line description", () => {
    expect(renderInfo({ description: "Line 1\nLine 2" })).toBe(
      "/**\n * @description Line 1\n * Line 2\n * @generated by openapi-shape.\n */",
    );
  });
  it("escapes comment terminators", () => {
    expect(renderInfo({ title: "A */ B" })).toBe(
      "/**\n * A *\\/ B\n *\n * @generated by openapi-shape.\n */",
    );
  });
});
