import { describe, expect, it } from "vitest";
import { renderHeader } from "../../../src/core/render/header";

describe("renderHeader: default", () => {
  it("renders title + version + description + @generated", () => {
    expect(renderHeader({ title: "T", version: "1.0", description: "D" })).toBe(
      "/**\n * T\n *\n * @version 1.0\n * @description D\n * @generated by openapi-shape.\n */",
    );
  });
  it("renders @generated only when info is empty", () => {
    expect(renderHeader({})).toBe("/**\n * @generated by openapi-shape.\n */");
  });
  it("expands multi-line description", () => {
    expect(renderHeader({ description: "Line 1\nLine 2" })).toBe(
      "/**\n * @description Line 1\n * Line 2\n * @generated by openapi-shape.\n */",
    );
  });
  it("escapes comment terminators", () => {
    expect(renderHeader({ title: "A */ B" })).toBe(
      "/**\n * A *\\/ B\n *\n * @generated by openapi-shape.\n */",
    );
  });
});

describe("renderHeader: option", () => {
  it("false → null", () => {
    expect(renderHeader({ title: "T" }, false)).toBeNull();
  });
  it("function delegates", () => {
    expect(renderHeader({ title: "T" }, (i) => `// ${i.title ?? ""}`)).toBe("// T");
  });
});
