import type { DocumentInfo } from "../ir/types";

export type HeaderOption = undefined | false | ((info: DocumentInfo) => string);

export function renderHeader(info: DocumentInfo, option: HeaderOption = undefined): string | null {
  if (option === false) return null;
  if (typeof option === "function") return option(info);
  return defaultHeader(info);
}

function defaultHeader(info: DocumentInfo): string {
  const lines: string[] = [];
  if (info.title) lines.push(info.title);

  const tagLines: string[] = [];
  if (info.version) tagLines.push(`@version ${info.version}`);
  if (info.description) {
    const [first, ...rest] = info.description.split("\n");
    tagLines.push(`@description ${first}`, ...rest);
  }
  tagLines.push("@generated by openapi-shape.");

  if (lines.length) lines.push("");
  lines.push(...tagLines);

  return `/**\n${lines.map((line) => ` *${line ? " " + line : ""}`).join("\n")}\n */`;
}
