import type { DocumentInfo } from "../contract/model"

export function renderInfo(info: DocumentInfo): string {
  const lines: string[] = []
  if (info.title) lines.push(singleLine(info.title))
  if (info.version) lines.push(`Version: ${singleLine(info.version)}`)
  if (info.description) lines.push(singleLine(info.description))
  if (lines.length > 0) lines.push("------")
  lines.push("Generated by openapi-shape.")
  return lines.map((line) => `// ${line}`).join("\n")
}

// Collapse all whitespace, including `\r` and Unicode line separators, which
// are JS line terminators and would otherwise escape the `//` comment.
function singleLine(s: string): string {
  return s.replaceAll(/\s+/g, " ").trim()
}
