import type { DocumentInfo } from "../contract/contract"
import { escapeCommentText } from "./format"

export function renderInfo(info: DocumentInfo): string {
  const lines: string[] = []
  if (info.title) lines.push(escapeCommentText(info.title))

  const tagLines: string[] = []
  if (info.version) tagLines.push(`@version ${escapeCommentText(info.version)}`)
  if (info.description) {
    const [first, ...rest] = escapeCommentText(info.description).split("\n")
    tagLines.push(`@description ${first}`, ...rest)
  }
  tagLines.push("@generated by openapi-shape.")

  if (lines.length > 0) lines.push("")
  lines.push(...tagLines)

  return `/**\n${lines.map((line) => ` *${line ? ` ${line}` : ""}`).join("\n")}\n */`
}
