import type { DocumentInfo } from "../contract/contract"

export function renderInfo(info: DocumentInfo): string {
  const lines: string[] = []
  if (info.title) lines.push(singleLine(info.title))
  if (info.version) lines.push(`Version: ${singleLine(info.version)}`)
  if (info.description) lines.push(singleLine(info.description))
  if (lines.length > 0) lines.push("------")
  lines.push("Generated by openapi-shape.")
  return lines.map((line) => `// ${line}`).join("\n")
}

function singleLine(s: string): string {
  return s.replaceAll(/\s*\n\s*/g, " ").trim()
}
