import { readSource } from "./parser";
import { resolveRefs } from "./refs";
import { injectDiscriminators } from "./discriminator";
import { generateEndpoints } from "./endpoints";
import { generateSchemas } from "./schemas";

function generateHeader(info: any): string {
  const lines: string[] = [];
  const title = typeof info?.title === "string" ? info.title.trim() : "";
  const version = typeof info?.version === "string" ? info.version.trim() : "";
  const description = typeof info?.description === "string" ? info.description.trim() : "";

  if (title) lines.push(title);

  const tagLines: string[] = [];
  if (version) tagLines.push(`@version ${version}`);
  if (description) {
    const [first, ...rest] = description.split("\n");
    tagLines.push(`@description ${first}`, ...rest);
  }
  tagLines.push("@generated by openapi-shape.");

  if (lines.length) lines.push("");
  lines.push(...tagLines);

  return `/**\n${lines.map((line) => ` *${line ? " " + line : ""}`).join("\n")}\n */`;
}

export function generate(openapi: any): string {
  const resolvedOpenapi = resolveRefs(openapi);
  const injectedOpenapi = injectDiscriminators(resolvedOpenapi);
  const parts: string[] = [generateHeader(injectedOpenapi.info)];

  if (injectedOpenapi.paths) {
    parts.push(generateEndpoints(injectedOpenapi.paths));
  }

  if (injectedOpenapi.components?.schemas) {
    parts.push(generateSchemas(injectedOpenapi.components.schemas));
  }

  return parts.join("\n\n") + "\n";
}

export async function generateFromSource(source: string): Promise<string> {
  const openapi = await readSource(source);
  return generate(openapi);
}
